### ISSUE TITLE
Medusa 3D Issue

### ISSUE THREAD

**Issue by thunderbolt78** [gamescomputersplay/sudoku-solver#3]
hi are you able to check the medusa function ? i get this error 

000000030000003962004080000009002004080050000012460000000000000095000107160007203

Initial puzzle: complete cells 25 /81. Candidates to remove: 448
Traceback (most recent call last):
  File "h:\sodoku\sudoku-solver.py", line 1017, in <module>
    solution1 = solve_from_line(puzzle, verbose=True)
  File "h:\sodoku\sudoku-solver.py", line 991, in solve_from_line
    return line_from_solution(solve(s_np, verbose))
  File "h:\sodoku\sudoku-solver.py", line 928, in solve
    r8 = medusa_3d(puzzle)
  File "h:\sodoku\sudoku-solver.py", line 776, in medusa_3d
    count += empty_by_color(s, a, b)
  File "h:\sodoku\sudoku-solver.py", line 753, in empty_by_color
    s[cell[0]].remove(cell[1])
ValueError: list.remove(x): x not in list

are you able to add more strategies ?

**Comment by gamescomputersplay** [comment]
HI thunderbolt78,

Thanks for finding the bug.
Well, I added the condition that catches that error and now it seems to work just fine.

I must say, the code has been written a few years back and not that high quality really. I have next to zero idea what these methods do and I am the one who wrote them... That's how you know the code is not good.

I am planning to go back and maybe rewrite everything from scratch - that would be a great exercise in better code writing. But I will probably not get around to do it for a while. I am doing a total rewrite of Minesweeper bot now, and I have a few things in mind after that. But maybe in a few months it would be Sudoku time again.

So, thanks again for the bug and for interesting in the code. Apologies for the mess it is, though. I am writing a much better (even if I say so myself) code these days.

Best,
Dmitry, Games Computers Play
